version: '3'

services:
  automation-test:
    image: automation-test
    build: .
    ports:
      - 8080:8080  
    command: "npm run serve"
    
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:6.6.0"
    depends_on:
      - automation-test
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://automation-test:8000
    command: npx cypress-tags run --env TAGS=@ui --reporter junit --reporter-options mochaFile=results/my-test-output.xml,toConsole=true
    # share the current folder as volume to avoid copying
    working_dir: /cypress
    volumes:
      - ./:/cypress